### ISSUE TITLE
Bad pixel monitor crash

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwql#1148]
From the Jan 7, 2023 log file:

FAILURE working on NIS_CEN:
01/07/2023 04:32:28 AM INFO: Pipeline call requestion calibrated extensions defaultdict(<function BadPixels.process.<locals>.<lambda> at 0x7f5c43683a60>, {})
01/07/2023 04:32:28 AM INFO: Dispatching celery tasks
01/07/2023 04:32:28 AM INFO: Celery tasks submitted.
01/07/2023 04:32:28 AM INFO: Waiting for task results
01/07/2023 04:32:28 AM INFO: Finished retrieving results
01/07/2023 04:32:28 AM INFO: Releasing locks
01/07/2023 04:32:28 AM INFO: Finished releasing locks
01/07/2023 04:32:28 AM INFO: Pipeline Call Completed
01/07/2023 04:32:28 AM CRITICAL: Traceback (most recent call last):
  File "logging_functions.py", line 290, in wrapped
    func(*args, **kwargs)
  File "logging_functions.py", line 255, in wrapped
    func(*args, **kwargs)
  File "shared_tasks.py", line 167, in _caller
    ret_value = run_func(*args, **kwargs)
  File "bad_pixel_monitor.py", line 1183, in run
    self.process(flat_uncal_files, flat_rate_files, flat_file_count_threshold, dark_uncal_files, dark_rate_files, dark_file_count_threshold)
  File "bad_pixel_monitor.py", line 834, in process
    min_illum_time = min(illuminated_obstimes)
ValueError: min() arg is an empty sequence

**Comment by bhilbert4** [comment]
Bad pixel monitor is now working correctly
