### ISSUE TITLE
Check filesystem glob for dark current monitor

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwql#1149]
Jan 7, 2023 log (on ops):
Some apertures (MIRI XXX) show mast query returned a number of new files, but the files were not found in the filesystem. Check to be sure this is actually true.

**Comment by bhilbert4** [comment]
In the same log, there were a number of pipeline failures, but the ultimate cause isn't clear:

Also, pipeline failures: 
01/07/2023 09:41:03 AM INFO:    Starting jw01484088001_02201_00001_nrs1 with ID 611f21a3-094e-4146-91bc-541587fec36b
01/07/2023 09:41:03 AM INFO: Celery tasks submitted.
01/07/2023 09:41:03 AM INFO: Waiting for task results
01/07/2023 09:41:03 AM INFO:    Waiting for jw01484116001_02201_00001_nrs1 (4ec08754-fa81-43d8-8272-81581282b41b)
01/07/2023 10:01:17 AM ERROR:   Pipeline processing failed for jw01484116001_02201_00001_nrs1
01/07/2023 10:01:17 AM ERROR:   Processing raised 5 is not one of [1, 4]

Failed validating '<unset>' in schema:
    '<unset>'

On instance:
    '<unset>'
01/07/2023 10:01:17 AM INFO:    Waiting for jw01484098001_03201_00001_nrs1 (e0951340-9694-4de3-8cb4-581cc9ecaab7)
01/07/2023 10:01:26 AM ERROR:   Pipeline processing failed for jw01484098001_03201_00001_nrs1
01/07/2023 10:01:26 AM ERROR:   Processing raised 5 is not one of [1, 4]

Failed validating '<unset>' in schema:
    '<unset>'

AND THEN A LATER FAILURE THAT CRASHED THE MONITOR:
01/07/2023 10:04:30 AM INFO: Finished retrieving results
01/07/2023 10:04:30 AM INFO: Releasing locks
01/07/2023 10:04:30 AM INFO:    Released Lock jw01484116001_02201_00001_nrs1
01/07/2023 10:04:30 AM INFO:    Released Lock jw01484098001_03201_00001_nrs1
01/07/2023 10:04:30 AM INFO:    Released Lock jw01484114001_02201_00001_nrs1
01/07/2023 10:04:30 AM INFO:    Released Lock jw01484104001_02301_00001_nrs1
01/07/2023 10:04:30 AM INFO:    Released Lock jw01484115001_02201_00001_nrs1
01/07/2023 10:04:30 AM INFO:    Released Lock jw01484118001_02301_00001_nrs1
01/07/2023 10:04:30 AM INFO:    Released Lock jw01484106001_02301_00001_nrs1
01/07/2023 10:04:30 AM INFO:    Released Lock jw01484095001_04201_00001_nrs1
01/07/2023 10:04:30 AM INFO:    Released Lock jw01484101001_02301_00001_nrs1
01/07/2023 10:04:30 AM INFO:    Released Lock jw01484099001_03201_00001_nrs1
01/07/2023 10:04:30 AM INFO:    Released Lock jw01484105001_02301_00001_nrs1
01/07/2023 10:04:30 AM INFO:    Released Lock jw01484096001_02201_00001_nrs1
01/07/2023 10:04:30 AM INFO:    Released Lock jw01484107001_03301_00001_nrs1
01/07/2023 10:04:30 AM INFO:    Released Lock jw01484117001_02201_00001_nrs1
01/07/2023 10:04:30 AM INFO:    Released Lock jw01484100001_02301_00001_nrs1
01/07/2023 10:04:30 AM INFO:    Released Lock jw01484169001_02201_00001_nrs1
01/07/2023 10:04:30 AM INFO:    Released Lock jw01484088001_02201_00001_nrs1
01/07/2023 10:04:30 AM INFO: Finished releasing locks
01/07/2023 10:04:30 AM INFO: Pipeline Call Completed
01/07/2023 10:04:30 AM INFO:    Slope images to use in the dark monitor for nirspec, NRS1_FULL:
01/07/2023 10:04:30 AM CRITICAL: Traceback (most recent call last):
  File "logging_functions.py", line 290, in wrapped
    func(*args, **kwargs)
  File "/logging_functions.py", line 255, in wrapped
    func(*args, **kwargs)
  File "shared_tasks.py", line 167, in _caller
    ret_value = run_func(*args, **kwargs)
  File "dark_monitor.py", line 777, in run
    self.process(dark_files)
  File "dark_monitor.py", line 491, in process
    min_time = np.min(obs_times)
  File "<__array_function__ internals>", line 180, in amin
  File "python3.8/site-packages/numpy/core/fromnumeric.py", line 2918, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "python3.8/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
