### ISSUE TITLE
Readnoise monitor crashing

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwql#1150]
CRASHED: in log for Jan 7 (ops):
01/07/2023 10:23:35 AM INFO:    Working on file: nirspec_nrs1_full/jw01484101001_02301_00001_nrs1_uncal.fits
01/07/2023 10:23:35 AM WARNING: Calibrated file nirspec_nrs1_full/jw01484101001_02301_00001_nrs1_refpix.fits not found
01/07/2023 10:23:35 AM WARNING: Skipping file nirspec_nrs1_full/jw01484101001_02301_00001_nrs1_uncal.fits
01/07/2023 10:23:35 AM INFO:    Working on file: nirspec_nrs1_full/jw01484098001_03201_00001_nrs1_uncal.fits
01/07/2023 10:23:35 AM WARNING: Calibrated file nirspec_nrs1_full/jw01484098001_03201_00001_nrs1_refpix.fits not found
01/07/2023 10:23:35 AM WARNING: Skipping file nirspec_nrs1_full/jw01484098001_03201_00001_nrs1_uncal.fits
01/07/2023 10:23:35 AM INFO:    Working on file: /nirspec_nrs1_full/jw01484099001_03201_00001_nrs1_uncal.fits
01/07/2023 10:23:35 AM INFO:    Amplifier boundaries: {'1': [(4, 2044, 1), (4, 512, 1)], '2': [(4, 2044, 1), (512, 1024, 1)], '3': [(4, 2044, 1), (1024, 1536, 1)], '4': [(4, 2044, 1), (1536, 2044, 1)]}
01/07/2023 10:23:36 AM INFO:    Creating readnoise image
01/07/2023 10:23:36 AM WARNING: Degrees of freedom <= 0 for slice

01/07/2023 10:23:36 AM WARNING: invalid value encountered in divide

01/07/2023 10:23:36 AM WARNING: invalid value encountered in divide

01/07/2023 10:23:36 AM WARNING: Input data contains invalid values (NaNs or infs), which were automatically clipped.
01/07/2023 10:23:36 AM CRITICAL: Traceback (most recent call last):
  File "logging_functions.py", line 290, in wrapped
    func(*args, **kwargs)
  File "logging_functions.py", line 255, in wrapped
    func(*args, **kwargs)
  File "shared_tasks.py", line 167, in _caller
    ret_value = run_func(*args, **kwargs)
  File "readnoise_monitor.py", line 637, in run
    self.process(new_files)
  File "readnoise_monitor.py", line 455, in process
    full_image_mean, full_image_stddev = np.nanmean(clipped), np.nanstd(clipped)
  File "<__array_function__ internals>", line 180, in nanmean
  File "python3.8/site-packages/numpy/lib/nanfunctions.py", line 1048, in nanmean
    avg = _divide_by_count(tot, cnt, out=out)
  File "python3.8/site-packages/numpy/lib/nanfunctions.py", line 215, in _divide_by_count
    return np.divide(a, b, out=a, casting='unsafe')
ValueError: output array is read-only

**Comment by bhilbert4** [comment]
Readnoise monitor is now working correctly
