### ISSUE TITLE
Dark Monitor crashing with IndexError

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#524]
See traceback from recent log file:

```
11/12/2019 15:40:32 PM INFO: Working on aperture NRCA5_TAGRISMTS32_F405N in nircam
11/12/2019 15:40:32 PM INFO: 	No query history for NRCA5_TAGRISMTS32_F405N. Beginning search date will be set to 57357.0.
11/12/2019 15:40:32 PM INFO: 	Query times: 57357.0 58799.8603127774
11/12/2019 15:40:32 PM INFO: 	Aperture: NRCA5_TAGRISMTS32_F405N, new entries: 0
11/12/2019 15:40:32 PM CRITICAL: Traceback (most recent call last):
  File "/home/jwqladm/repositories/jwql/jwql/utils/logging_functions.py", line 279, in wrapped
    func(*args, **kwargs)
  File "/home/jwqladm/repositories/jwql/jwql/utils/logging_functions.py", line 244, in wrapped
    func(*args, **kwargs)
  File "dark_monitor.py", line 797, in run
    len(new_entries), instrument, aperture, file_count_threshold[0]))
  File "astropy/table/_column_mixins.pyx", line 74, in astropy.table._column_mixins._ColumnGetitemShim.__getitem__
  File "astropy/table/_column_mixins.pyx", line 57, in astropy.table._column_mixins.base_getitem
  File "astropy/table/_column_mixins.pyx", line 69, in astropy.table._column_mixins.column_getitem
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by bhilbert4** [comment]
This is because the NRCA5_TAGRISMTS32_F405N aperture is not present in the dark_monitor_file_thrsholds.txt file.
