### ISSUE TITLE
Dark monitor currently failing

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#551]
```
03/17/2020 03:04:31 AM INFO: Working on aperture NRCA5_TAGRISMTS32_F405N in nircam
03/17/2020 03:04:31 AM INFO: 	No query history for NRCA5_TAGRISMTS32_F405N. Beginning search date will be set to 57357.0.
03/17/2020 03:04:31 AM INFO: 	Query times: 57357.0 58925.29234513522
03/17/2020 03:04:31 AM INFO: 	Aperture: NRCA5_TAGRISMTS32_F405N, new entries: 0
03/17/2020 03:04:32 AM CRITICAL: Traceback (most recent call last):
  File "/home/jwqladm/repositories/jwql/jwql/utils/logging_functions.py", line 279, in wrapped
    func(*args, **kwargs)
  File "/home/jwqladm/repositories/jwql/jwql/utils/logging_functions.py", line 244, in wrapped
    func(*args, **kwargs)
  File "/home/jwqladm/repositories/jwql/jwql/instrument_monitors/common_monitors/dark_monitor.py", line 797, in run
    len(new_entries), instrument, aperture, file_count_threshold[0]))
  File "astropy/table/_column_mixins.pyx", line 74, in astropy.table._column_mixins._ColumnGetitemShim.__getitem__
  File "astropy/table/_column_mixins.pyx", line 57, in astropy.table._column_mixins.base_getitem
  File "astropy/table/_column_mixins.pyx", line 69, in astropy.table._column_mixins.column_getitem
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by bourque** [comment]
Oops, I just realized this is redundant with #524
