### ISSUE TITLE
Dark Monitor not handling absent data

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#618]
The Dark Monitor is crashing int he case where data is not able to be retrieved:

```
08/24/2020 03:00:56 AM INFO: Working on aperture MIRIM_FULL in miri
08/24/2020 03:00:56 AM INFO: 	No query history for MIRIM_FULL. Beginning search date will be set to 57357.0.
08/24/2020 03:00:56 AM INFO: 	Query times: 57357.0 59085.29225825882
08/24/2020 03:00:57 AM INFO: 	Aperture: MIRIM_FULL, new entries: 12
08/24/2020 03:00:57 AM INFO: 	Sufficient new dark files found for miri, MIRIM_FULL to run the dark monitor.
08/24/2020 03:00:57 AM WARNING: 		Unable to locate jw00619044001_02101_00001_mirimage_dark.fits in filesystem. Not including in processing.
08/24/2020 03:00:57 AM WARNING: 		Unable to locate jw00873010001_02101_00001_mirimage_dark.fits in filesystem. Not including in processing.
08/24/2020 03:00:57 AM WARNING: 		Unable to locate jw00873014001_02101_00001_mirimage_dark.fits in filesystem. Not including in processing.
08/24/2020 03:00:57 AM WARNING: 		Unable to locate jw00873006001_02101_00001_mirimage_dark.fits in filesystem. Not including in processing.
08/24/2020 03:00:57 AM WARNING: 		Unable to locate jw00811002001_02102_00001_mirimage_dark.fits in filesystem. Not including in processing.
08/24/2020 03:00:57 AM WARNING: 		Unable to locate jw00823003001_02102_00001_mirimage_dark.fits in filesystem. Not including in processing.
08/24/2020 03:00:57 AM WARNING: 		Unable to locate jw00619051001_02101_00001_mirimage_dark.fits in filesystem. Not including in processing.
08/24/2020 03:00:57 AM WARNING: 		Unable to locate jw00619058001_02101_00001_mirimage_dark.fits in filesystem. Not including in processing.
08/24/2020 03:00:57 AM WARNING: 		Unable to locate jw00630009001_02101_00001_mirimage_dark.fits in filesystem. Not including in processing.
08/24/2020 03:00:57 AM WARNING: 		Unable to locate jw00619079001_02101_00001_mirimage_dark.fits in filesystem. Not including in processing.
08/24/2020 03:00:57 AM WARNING: 		Unable to locate jw00619086001_02101_00001_mirimage_dark.fits in filesystem. Not including in processing.
08/24/2020 03:00:57 AM WARNING: 		Unable to locate jw00619093001_02101_00001_mirimage_dark.fits in filesystem. Not including in processing.
08/24/2020 03:00:57 AM INFO: 	New_filenames: []
08/24/2020 03:00:57 AM INFO: 	Data dir: /grp/jwst/ins/jwql/outputs/dark_monitor/data/miri_mirim_full
08/24/2020 03:00:57 AM INFO: 	Copied to working dir: []
08/24/2020 03:00:57 AM INFO: 	Not copied: []
08/24/2020 03:00:57 AM CRITICAL: Traceback (most recent call last):
  File "/home/jwqladm/repositories/jwql/jwql/utils/logging_functions.py", line 284, in wrapped
    func(*args, **kwargs)
  File "/home/jwqladm/repositories/jwql/jwql/utils/logging_functions.py", line 249, in wrapped
    func(*args, **kwargs)
  File "/home/jwqladm/repositories/jwql/jwql/instrument_monitors/common_monitors/dark_monitor.py", line 791, in run
    self.process(dark_files)
  File "/home/jwqladm/repositories/jwql/jwql/instrument_monitors/common_monitors/dark_monitor.py", line 517, in process
    self.get_metadata(file_list[0])
IndexError: list index out of range

08/24/2020 03:00:57 AM CRITICAL: CRASHED
```

We should figure out why data is not able to be found, but also make sure that the code can move on to other instruments/apertures in this situation without crashing completely.

**Comment by bourque** [comment]
This is a roadblock for #600
