### ISSUE TITLE
Bad Pixel Monitor crashes on data from latest DMS build

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#761]
**Describe the bug**
The `bad_pixel_monitor` crashes on MIRI data from the latest DMS build (#748)

**To Reproduce**
Run the `bad_pixel_monitor.py` script on the dev server which points to the latest DMS build

Here is some of the log file that contains the traceback (some info has been clipped for redundancy and not exposing directory structures)

```
07/19/2021 11:35:45 AM INFO: Working on aperture ('MIRIMAGE', 'MIRIM_FULL') in miri
07/19/2021 11:35:45 AM INFO: 	No query history for MIRIMAGE. Beginning search date will be set to 57357.0.
07/19/2021 11:35:45 AM INFO: 	No query history for MIRIMAGE. Beginning search date will be set to 57357.0.
07/19/2021 11:35:45 AM INFO: 	Flat field query times: 57357.0 59414.649822773325
07/19/2021 11:35:45 AM INFO: 	Dark current query times: 57357.0 59414.649822773325
07/19/2021 11:35:45 AM WARNING: 		Unable to locate jw99002001002_03102_00001_mirimage_uncal.fits in filesystem. Not including in processing.
07/19/2021 11:35:45 AM WARNING: 		Unable to locate jw99002001002_03102_00001_mirimage_uncal.fits in filesystem. Not including in processing.
07/19/2021 11:35:45 AM INFO: 	Bad pixels from flats skipped. 3 new flat files for miri,('MIRIMAGE', 'MIRIM_FULL') found. 10 new files are required to run bad pixelsfrom flats portion of monitor.
07/19/2021 11:35:45 AM WARNING: 		Unable to locate jw00619044001_02101_00001_mirimage_uncal.fits in filesystem. Not including in processing.
07/19/2021 11:35:45 AM WARNING: 		Unable to locate jw00619051001_02101_00001_mirimage_uncal.fits in filesystem. Not including in processing.
07/19/2021 11:35:45 AM WARNING: 		Unable to locate jw00619058001_02101_00001_mirimage_uncal.fits in filesystem. Not including in processing.
07/19/2021 11:35:45 AM WARNING: 		Unable to locate jw00619079001_02101_00001_mirimage_uncal.fits in filesystem. Not including in processing.
07/19/2021 11:35:45 AM WARNING: 		Unable to locate jw00619086001_02101_00001_mirimage_uncal.fits in filesystem. Not including in processing.
07/19/2021 11:35:45 AM WARNING: 		Unable to locate jw00619107001_02101_00001_mirimage_uncal.fits in filesystem. Not including in processing.
07/19/2021 11:35:45 AM WARNING: 		Unable to locate jw00619121001_02101_00001_mirimage_uncal.fits in filesystem. Not including in processing.
07/19/2021 11:35:45 AM INFO: 	Sufficient new files found for miri, ('MIRIMAGE', 'MIRIM_FULL') to run thebad pixel from darks portion of the monitor.
07/19/2021 11:35:45 AM INFO: 	New entries: 20
07/19/2021 11:35:45 AM INFO: 	New dark observations: 
07/19/2021 11:35:45 AM INFO: 	Data dir: outputs/dev/bad_pixel_monitor/data/miri_mirimage
07/19/2021 11:35:45 AM INFO: 	Copied to data dir: ['/grp/jwst/ins/jwql/outputs/dev/bad_pixel_monitor/data/miri_mirimage/jw00619100001_02101_00001_mirimage_uncal.fits', '/grp/jwst/ins/jwql/outputs/dev/bad_pixel_monitor/data/miri_mirimage/jw00619114001_02101_00001_mirimage_uncal.fits', '/grp/jwst/ins/jwql/outputs/dev/bad_pixel_monitor/data/miri_mirimage/jw00673038001_02201_00001_mirimage_uncal.fits', '/grp/jwst/ins/jwql/outputs/dev/bad_pixel_monitor/data/miri_mirimage/jw00712021001_02101_00001_mirimage_uncal.fits', '/grp/jwst/ins/jwql/outputs/dev/bad_pixel_monitor/data/miri_mirimage/jw00811003001_02101_00001_mirimage_uncal.fits', '/grp/jwst/ins/jwql/outputs/dev/bad_pixel_monitor/data/miri_mirimage/jw00823005001_02101_00001_mirimage_uncal.fits', '/grp/jwst/ins/jwql/outputs/dev/bad_pixel_monitor/data/miri_mirimage/jw00823006001_02101_00001_mirimage_uncal.fits', '/grp/jwst/ins/jwql/outputs/dev/bad_pixel_monitor/data/miri_mirimage/jw00823007001_02101_00001_mirimage_uncal.fits', '/grp/jwst/ins/jwql/outputs/dev/bad_pixel_monitor/data/miri_mirimage/jw00823008001_02101_00001_mirimage_uncal.fits', '/grp/jwst/ins/jwql/outputs/dev/bad_pixel_monitor/data/miri_mirimage/jw00830003001_02102_00001_mirimage_uncal.fits', '/grp/jwst/ins/jwql/outputs/dev/bad_pixel_monitor/data/miri_mirimage/jw00830003001_02102_00002_mirimage_uncal.fits', '/grp/jwst/ins/jwql/outputs/dev/bad_pixel_monitor/data/miri_mirimage/jw00846002001_02101_00001_mirimage_uncal.fits', '/grp/jwst/ins/jwql/outputs/dev/bad_pixel_monitor/data/miri_mirimage/jw00846002001_02101_00002_mirimage_uncal.fits', '/grp/jwst/ins/jwql/outputs/dev/bad_pixel_monitor/data/miri_mirimage/jw00619093001_02101_00001_mirimage_uncal.fits', '/grp/jwst/ins/jwql/outputs/dev/bad_pixel_monitor/data/miri_mirimage/jw00630009001_02101_00001_mirimage_uncal.fits', '/grp/jwst/ins/jwql/outputs/dev/bad_pixel_monitor/data/miri_mirimage/jw00811002001_02102_00001_mirimage_uncal.fits', '/grp/jwst/ins/jwql/outputs/dev/bad_pixel_monitor/data/miri_mirimage/jw00823003001_02102_00001_mirimage_uncal.fits', '/grp/jwst/ins/jwql/outputs/dev/bad_pixel_monitor/data/miri_mirimage/jw00873006001_02101_00001_mirimage_uncal.fits', '/grp/jwst/ins/jwql/outputs/dev/bad_pixel_monitor/data/miri_mirimage/jw00873010001_02101_00001_mirimage_uncal.fits', '/grp/jwst/ins/jwql/outputs/dev/bad_pixel_monitor/data/miri_mirimage/jw00873014001_02101_00001_mirimage_uncal.fits']
07/19/2021 11:35:45 AM INFO: 	Not copied (failed, or missing from filesystem): []
07/19/2021 11:35:45 AM INFO: Detector1Pipeline instance created.
07/19/2021 11:35:45 AM INFO: GroupScaleStep instance created.
07/19/2021 11:35:45 AM INFO: DQInitStep instance created.
07/19/2021 11:35:45 AM INFO: SaturationStep instance created.
07/19/2021 11:35:45 AM INFO: IPCStep instance created.
07/19/2021 11:35:45 AM INFO: SuperBiasStep instance created.
07/19/2021 11:35:45 AM INFO: RefPixStep instance created.
07/19/2021 11:35:45 AM INFO: RscdStep instance created.
07/19/2021 11:35:45 AM INFO: FirstFrameStep instance created.
07/19/2021 11:35:45 AM INFO: LastFrameStep instance created.
07/19/2021 11:35:45 AM INFO: LinearityStep instance created.
07/19/2021 11:35:45 AM INFO: DarkCurrentStep instance created.
07/19/2021 11:35:45 AM INFO: ResetStep instance created.
07/19/2021 11:35:45 AM INFO: PersistenceStep instance created.
07/19/2021 11:35:45 AM INFO: JumpStep instance created.
07/19/2021 11:35:45 AM INFO: RampFitStep instance created.
07/19/2021 11:35:45 AM INFO: GainScaleStep instance created.
07/19/2021 11:35:46 AM INFO: Detector1Pipeline instance created.
07/19/2021 11:35:46 AM INFO: GroupScaleStep instance created.
07/19/2021 11:35:46 AM INFO: DQInitStep instance created.
07/19/2021 11:35:46 AM INFO: SaturationStep instance created.
07/19/2021 11:35:46 AM INFO: IPCStep instance created.
07/19/2021 11:35:46 AM INFO: SuperBiasStep instance created.
07/19/2021 11:35:46 AM INFO: RefPixStep instance created.
07/19/2021 11:35:46 AM INFO: RscdStep instance created.
07/19/2021 11:35:46 AM INFO: FirstFrameStep instance created.
07/19/2021 11:35:46 AM INFO: LastFrameStep instance created.
07/19/2021 11:35:46 AM INFO: LinearityStep instance created.
07/19/2021 11:35:46 AM INFO: DarkCurrentStep instance created.
07/19/2021 11:35:46 AM INFO: ResetStep instance created.
07/19/2021 11:35:46 AM INFO: PersistenceStep instance created.
07/19/2021 11:35:46 AM INFO: JumpStep instance created.
07/19/2021 11:35:46 AM INFO: RampFitStep instance created.

...

07/19/2021 11:35:46 AM INFO: GainScaleStep instance created.
07/19/2021 11:35:46 AM INFO: Detector1Pipeline instance created.
07/19/2021 11:35:46 AM INFO: GroupScaleStep instance created.
07/19/2021 11:35:46 AM INFO: DQInitStep instance created.
07/19/2021 11:35:46 AM INFO: SaturationStep instance created.
07/19/2021 11:35:46 AM INFO: IPCStep instance created.
07/19/2021 11:35:46 AM INFO: SuperBiasStep instance created.
07/19/2021 11:35:46 AM INFO: RefPixStep instance created.
07/19/2021 11:35:46 AM INFO: RscdStep instance created.
07/19/2021 11:35:46 AM INFO: FirstFrameStep instance created.
07/19/2021 11:35:46 AM INFO: LastFrameStep instance created.
07/19/2021 11:35:46 AM INFO: LinearityStep instance created.
07/19/2021 11:35:46 AM INFO: DarkCurrentStep instance created.
07/19/2021 11:35:46 AM INFO: ResetStep instance created.
07/19/2021 11:35:46 AM INFO: PersistenceStep instance created.
07/19/2021 11:35:46 AM INFO: JumpStep instance created.
07/19/2021 11:35:46 AM INFO: RampFitStep instance created.
07/19/2021 11:35:46 AM INFO: GainScaleStep instance created.
07/19/2021 11:35:49 AM WARNING: /home/svc_jwqladm_dev/jwql/miniconda3/envs/jwql-3.7/lib/python3.7/site-packages/astropy/stats/sigma_clipping.py:308: AstropyUserWarning: Input data contains invalid values (NaNs or infs), which were automatically clipped.
  AstropyUserWarning)

07/19/2021 11:35:49 AM WARNING: /home/svc_jwqladm_dev/jwql/miniconda3/envs/jwql-3.7/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3420: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)

07/19/2021 11:35:49 AM WARNING: /home/svc_jwqladm_dev/jwql/miniconda3/envs/jwql-3.7/lib/python3.7/site-packages/numpy/core/_methods.py:188: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)

07/19/2021 11:35:49 AM WARNING: /home/svc_jwqladm_dev/jwql/miniconda3/envs/jwql-3.7/lib/python3.7/site-packages/numpy/core/_methods.py:262: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims, where=where)

07/19/2021 11:35:49 AM WARNING: /home/svc_jwqladm_dev/jwql/miniconda3/envs/jwql-3.7/lib/python3.7/site-packages/numpy/core/_methods.py:222: RuntimeWarning: invalid value encountered in true_divide
  subok=False)

07/19/2021 11:35:49 AM WARNING: /home/svc_jwqladm_dev/jwql/miniconda3/envs/jwql-3.7/lib/python3.7/site-packages/numpy/core/_methods.py:253: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)

07/19/2021 11:36:28 AM CRITICAL: Traceback (most recent call last):
  File "/jwql/jwql/jwql/utils/logging_functions.py", line 284, in wrapped
    func(*args, **kwargs)
  File "jwql/utils/logging_functions.py", line 249, in wrapped
    func(*args, **kwargs)
  File "bad_pixel_monitor.py", line 1046, in run
    self.process(flat_uncal_files, flat_rate_files, dark_uncal_files, dark_rate_files)
  File "bad_pixel_monitor.py", line 858, in process
    history='This file was created by JWQL', quality_check=False)
  File "/home/svc_jwqladm_dev/jwql/miniconda3/envs/jwql-3.7/lib/python3.7/site-packages/jwst_reffiles/bad_pixel_mask/bad_pixel_mask.py", line 429, in bad_pixels
    final_mask = np.bitwise_or(flatmask, darkmask)
TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

07/19/2021 11:36:28 AM CRITICAL: CRASHED
```

**Comment by bhilbert4** [comment]
I made some updates to the bad pixel code in the jwst_reffiles repo that I think should solve this issue.
https://github.com/spacetelescope/jwst_reffiles/pull/131
I'll check the log for the next run of the bad pixel monitor to confirm.
