### ISSUE TITLE
Readnoise Monitor crashes on data from latest DMS build

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#762]
**Describe the bug**
The `readnoise_monitor` crashes on MIRI data from the latest DMS build (#748)

**To Reproduce**
Run the `readnoise_monitor.py` script on the dev server which points to the latest DMS build

Here is some of the log file that contains the traceback (some info has been clipped for redundancy and not exposing directory structures)

```
07/19/2021 11:42:09 AM INFO: 	Working on file: outputs/dev/readnoise_monitor/data/miri_mirim_brightsky/jw00873005001_02101_00001_mirifushort_uncal.fits
07/19/2021 11:42:09 AM INFO: 	Running pipeline on /outputs/dev/readnoise_monitor/data/miri_mirim_brightsky/jw00873005001_02101_00001_mirifushort_uncal.fits
07/19/2021 11:42:11 AM INFO: DQInitStep instance created.
07/19/2021 11:42:11 AM INFO: Step DQInitStep running with args ('outputs/dev/readnoise_monitor/data/miri_mirim_brightsky/jw00873005001_02101_00001_mirifushort_uncal.fits',).
07/19/2021 11:42:11 AM INFO: Step DQInitStep parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': ''}
07/19/2021 11:42:11 AM DEBUG: Input model type Level1bModel does not match the requested model <class 'jwst.datamodels.ramp.RampModel'>. Cannot skip updating from FITS headers.
07/19/2021 11:42:12 AM INFO: Using MASK reference file references/jwst/jwst_miri_mask_0022.fits
07/19/2021 11:42:12 AM DEBUG: No ASDF information found. Cannot skip updating from FITS headers.
07/19/2021 11:42:12 AM DEBUG: ref substrt1=1, subsize1=1032, substrt2=1, subsize2=1024
07/19/2021 11:42:12 AM DEBUG: sci substrt1=1, subsize1=1032, substrt2=1, subsize2=1024
07/19/2021 11:42:12 AM INFO: Step DQInitStep done
07/19/2021 11:42:12 AM INFO: RefPixStep instance created.
07/19/2021 11:42:12 AM INFO: Step RefPixStep running with args (<RampModel(1, 16, 1024, 1032) from jw00873005001_02101_00001_mirifushort_uncal.fits>,).
07/19/2021 11:42:12 AM INFO: Step RefPixStep parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'odd_even_columns': True, 'use_side_ref_pixels': True, 'side_smoothing_length': 11, 'side_gain': 1.0, 'odd_even_rows': True}
07/19/2021 11:42:12 AM INFO: use_side_ref_pixels = True
07/19/2021 11:42:12 AM INFO: odd_even_columns = True
07/19/2021 11:42:12 AM INFO: side_smoothing_length = 11
07/19/2021 11:42:12 AM INFO: side_gain = 1.000000
07/19/2021 11:42:12 AM INFO: odd_even_rows = True
07/19/2021 11:42:12 AM INFO: Subtracting initial read from each integration
07/19/2021 11:42:12 AM INFO: Adding initial read back in
07/19/2021 11:42:12 AM INFO: Step RefPixStep done
07/19/2021 11:42:13 AM INFO: 	Pipeline complete. Output: outputs/dev/readnoise_monitor/data/miri_mirim_brightsky/jw00873005001_02101_00001_mirifushort_uncal_refpix.fits
07/19/2021 11:42:13 AM INFO: 	Amplifier boundaries: {'1': [(4, 1028, 4), (0, 1024, 1)], '2': [(5, 1028, 4), (0, 1024, 1)], '3': [(6, 1028, 4), (0, 1024, 1)], '4': [(7, 1028, 4), (0, 1024, 1)]}
07/19/2021 11:42:13 AM INFO: 	Creating stack of CDS difference frames
07/19/2021 11:42:13 AM INFO: 	Creating readnoise image
07/19/2021 11:42:15 AM INFO: 	Readnoise image saved to /outputs/dev/readnoise_monitor/data/miri_mirim_brightsky/jw00873005001_02101_00001_mirifushort_uncal_refpix_readnoise.fits
07/19/2021 11:42:15 AM INFO: 	Readnoise image stats: 13399.20041 +/- 13315.16238
07/19/2021 11:42:15 AM INFO: 	Readnoise image stats by amp: {'amp1_mean': 13401.957523689449, 'amp1_stddev': 13312.881117000146, 'amp1_n': array([57420,     0,     0,     0, 98210,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
       40644, 16232,     0,     0, 16234, 25226,     0,     0,     0,
        8178,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0]), 'amp1_bin_centers': array([  374.457764  ,  1123.37329199,  1872.28881999,  2621.20434799,
        3370.11987598,  4119.03540398,  4867.95093198,  5616.86645997,
        6365.78198797,  7114.69751597,  7863.61304396,  8612.52857196,
        9361.44409996, 10110.35962795, 10859.27515595, 11608.19068395,
       12357.10621194, 13106.02173994, 13854.93726794, 14603.85279593,
       15352.76832393, 16101.68385193, 16850.59937992, 17599.51490792,
       18348.43043591, 19097.34596391, 19846.26149191, 20595.1770199 ,
       21344.0925479 , 22093.0080759 , 22841.92360389, 23590.83913189,
       24339.75465989, 25088.67018788, 25837.58571588, 26586.50124388,
       27335.41677187, 28084.33229987, 28833.24782787, 29582.16335586,
       30331.07888386, 31079.99441186, 31828.90993985, 32577.82546785,
       33326.74099585, 34075.65652384, 34824.57205184, 35573.48757983,
       36322.40310783, 37071.31863583, 37820.23416382, 38569.14969182,
       39318.06521982, 40066.98074781, 40815.89627581, 41564.81180381,
       42313.7273318 , 43062.6428598 , 43811.5583878 , 44560.47391579,
       45309.38944379, 46058.30497179, 46807.22049978, 47556.13602778,
       48305.05155578, 49053.96708377, 49802.88261177, 50551.79813976,
       51300.71366776, 52049.62919576, 52798.54472375, 53547.46025175,
       54296.37577975, 55045.29130774, 55794.20683574, 56543.12236374,
       57292.03789173, 58040.95341973, 58789.86894773, 59538.78447572,
       60287.70000372, 61036.61553172, 61785.53105971, 62534.44658771,
       63283.36211571, 64032.2776437 , 64781.1931717 , 65530.1086997 ,
       66279.02422769]), 'amp2_mean': 13398.180153590465, 'amp2_stddev': 13315.952386198795, 'amp2_n': array([57421,     0,     0,     0, 98210,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
       40644, 16232,     0,     0, 16234, 25224,     0,     0,     0,
        8179,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0]), 'amp2_bin_centers': array([  374.5055601 ,  1123.51668031,  1872.52780052,  2621.53892072,
        3370.55004093,  4119.56116114,  4868.57228134,  5617.58340155,
        6366.59452176,  7115.60564196,  7864.61676217,  8613.62788238,
        9362.63900258, 10111.65012279, 10860.661243  , 11609.6723632 ,
       12358.68348341, 13107.69460362, 13856.70572382, 14605.71684403,
       15354.72796423, 16103.73908444, 16852.75020465, 17601.76132485,
       18350.77244506, 19099.78356527, 19848.79468547, 20597.80580568,
       21346.81692589, 22095.82804609, 22844.8391663 , 23593.85028651,
       24342.86140671, 25091.87252692, 25840.88364713, 26589.89476733,
       27338.90588754, 28087.91700775, 28836.92812795, 29585.93924816,
       30334.95036837, 31083.96148857, 31832.97260878, 32581.98372899,
       33330.99484919, 34080.0059694 , 34829.01708961, 35578.02820981,
       36327.03933002, 37076.05045023, 37825.06157043, 38574.07269064,
       39323.08381085, 40072.09493105, 40821.10605126, 41570.11717147,
       42319.12829167, 43068.13941188, 43817.15053208, 44566.16165229,
       45315.1727725 , 46064.1838927 , 46813.19501291, 47562.20613312,
       48311.21725332, 49060.22837353, 49809.23949374, 50558.25061394,
       51307.26173415, 52056.27285436, 52805.28397456, 53554.29509477,
       54303.30621498, 55052.31733518, 55801.32845539, 56550.3395756 ,
       57299.3506958 , 58048.36181601, 58797.37293622, 59546.38405642,
       60295.39517663, 61044.40629684, 61793.41741704, 62542.42853725,
       63291.43965746, 64040.45077766, 64789.46189787, 65538.47301808,
       66287.48413828]), 'amp3_mean': 13398.179374513982, 'amp3_stddev': 13315.95270738177, 'amp3_n': array([57421,     0,     0,     0, 98210,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
       40644, 16232,     0,     0, 16234, 25224,     0,     0,     0,
        8179,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0]), 'amp3_bin_centers': array([  374.50556294,  1123.51668883,  1872.52781472,  2621.53894061,
        3370.5500665 ,  4119.56119238,  4868.57231827,  5617.58344416,
        6366.59457005,  7115.60569594,  7864.61682183,  8613.62794771,
        9362.6390736 , 10111.65019949, 10860.66132538, 11609.67245127,
       12358.68357715, 13107.69470304, 13856.70582893, 14605.71695482,
       15354.72808071, 16103.73920659, 16852.75033248, 17601.76145837,
       18350.77258426, 19099.78371015, 19848.79483603, 20597.80596192,
       21346.81708781, 22095.8282137 , 22844.83933959, 23593.85046548,
       24342.86159136, 25091.87271725, 25840.88384314, 26589.89496903,
       27338.90609492, 28087.9172208 , 28836.92834669, 29585.93947258,
       30334.95059847, 31083.96172436, 31832.97285024, 32581.98397613,
       33330.99510202, 34080.00622791, 34829.0173538 , 35578.02847968,
       36327.03960557, 37076.05073146, 37825.06185735, 38574.07298324,
       39323.08410913, 40072.09523501, 40821.1063609 , 41570.11748679,
       42319.12861268, 43068.13973857, 43817.15086445, 44566.16199034,
       45315.17311623, 46064.18424212, 46813.19536801, 47562.20649389,
       48311.21761978, 49060.22874567, 49809.23987156, 50558.25099745,
       51307.26212333, 52056.27324922, 52805.28437511, 53554.295501  ,
       54303.30662689, 55052.31775278, 55801.32887866, 56550.34000455,
       57299.35113044, 58048.36225633, 58797.37338222, 59546.3845081 ,
       60295.39563399, 61044.40675988, 61793.41788577, 62542.42901166,
       63291.44013754, 64040.45126343, 64789.46238932, 65538.47351521,
       66287.4846411 ]), 'amp4_mean': 13398.179918149573, 'amp4_stddev': 13315.952047181077, 'amp4_n': array([57421,     0,     0,     0, 98210,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
       40644, 16232,     0,     0, 16234, 25224,     0,     0,     0,
        8179,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0]), 'amp4_bin_centers': array([  374.50555116,  1123.51665349,  1872.52775581,  2621.53885814,
        3370.54996046,  4119.56106278,  4868.57216511,  5617.58326743,
        6366.59436976,  7115.60547208,  7864.61657441,  8613.62767673,
        9362.63877906, 10111.64988138, 10860.6609837 , 11609.67208603,
       12358.68318835, 13107.69429068, 13856.705393  , 14605.71649533,
       15354.72759765, 16103.73869998, 16852.7498023 , 17601.76090462,
       18350.77200695, 19099.78310927, 19848.7942116 , 20597.80531392,
       21346.81641625, 22095.82751857, 22844.83862089, 23593.84972322,
       24342.86082554, 25091.87192787, 25840.88303019, 26589.89413252,
       27338.90523484, 28087.91633717, 28836.92743949, 29585.93854181,
       30334.94964414, 31083.96074646, 31832.97184879, 32581.98295111,
       33330.99405344, 34080.00515576, 34829.01625809, 35578.02736041,
       36327.03846273, 37076.04956506, 37825.06066738, 38574.07176971,
       39323.08287203, 40072.09397436, 40821.10507668, 41570.11617901,
       42319.12728133, 43068.13838365, 43817.14948598, 44566.1605883 ,
       45315.17169063, 46064.18279295, 46813.19389528, 47562.2049976 ,
       48311.21609993, 49060.22720225, 49809.23830457, 50558.2494069 ,
       51307.26050922, 52056.27161155, 52805.28271387, 53554.2938162 ,
       54303.30491852, 55052.31602085, 55801.32712317, 56550.33822549,
       57299.34932782, 58048.36043014, 58797.37153247, 59546.38263479,
       60295.39373712, 61044.40483944, 61793.41594177, 62542.42704409,
       63291.43814641, 64040.44924874, 64789.46035106, 65538.47145339,
       66287.48255571])}
07/19/2021 11:42:15 AM CRITICAL: Traceback (most recent call last):
  File "wql/jwql/jwql/utils/logging_functions.py", line 284, in wrapped
    func(*args, **kwargs)
  File "jwql/jwql/jwql/utils/logging_functions.py", line 249, in wrapped
    func(*args, **kwargs)
  File "readnoise_monitor.py", line 593, in run
    self.process(new_files)
  File "readnoise_monitor.py", line 447, in process
    reffile_mapping = crds.getreferences(parameters, reftypes=['readnoise'])
  File "jwql-3.7/lib/python3.7/site-packages/crds/core/heavy_client.py", line 128, in getreferences
    final_context, bestrefs, ignore_cache=ignore_cache)
  File "jwql-3.7/lib/python3.7/site-packages/crds/client/api.py", line 848, in cache_references
    wanted = _get_cache_filelist_and_report_errors(bestrefs)
  File "jwql-3.7/lib/python3.7/site-packages/crds/client/api.py", line 891, in _get_cache_filelist_and_report_errors
    raise last_error
crds.core.exceptions.CrdsLookupError: Error determining best reference for 'readnoise'  =   No match found.

07/19/2021 11:42:15 AM CRITICAL: CRASHED
```

**Comment by bsunnquist** [comment]
I can put in a fix for this. It looks like it isn't robust to missing reffiles like I thought it was.

My hunch is that we're now picking up rehearsal test data (GSEG, LRE, etc), which can include strange detector setups and test pattern data (which would also explain why the results for some of these images are so strange).

**Comment by bourque** [comment]
Thank you @bsunnquist!

Do you think the problem that you describe would exist when we are in operations?  Would it be easier to just not process rehearsal test data?

**Comment by bsunnquist** [comment]
Either way is fine on my end - if we still process it, I may just eventually cut the start range on my monitor plots to exclude any pre-launch data, so these strange test pattern results don't confuse people.

The test pattern data won't be an issue in commissioning/operations. Here is an example of it, basically the pixels values just increment from 1 to 65535 over and over, so any analysis/pipeline results are always strange looking.
<img width="638" alt="Screen Shot 2021-07-26 at 11 02 21 AM" src="https://user-images.githubusercontent.com/16088329/127016039-42711db2-e70a-4682-8ea4-8a73679cb72d.png">

I made the Readnoise Monitor robust to the other issue as well (missing reffiles) here https://github.com/spacetelescope/jwql/pull/766, so it won't crash it that scenario anymore. This should also be rare/non-existent in commissioning (could just be an issue if teams forget to make reffiles for certain modes).

**Comment by bourque** [comment]
Perfect, sounds great! Thanks
