### ISSUE TITLE
Dark Monitor crashes on data from latest DMS build

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#763]
**Describe the bug**
The `dark_monitor` crashes on NIRCam data from the latest DMS build (#748)

**To Reproduce**
Run the `dark_monitor.py` script on the dev server which points to the latest DMS build

Here is some of the log file that contains the traceback (some info has been clipped for redundancy and not exposing directory structures)

```
07/19/2021 11:50:56 AM INFO: 	Working on file: outputs/dev/dark_monitor/data/nircam_nrca1_full/jw00759141001_03101_00001_nrca1_dark.fits
07/19/2021 11:50:56 AM INFO: 	Pipeline steps that remain to be run:
07/19/2021 11:50:56 AM INFO: 		group_scale: False
07/19/2021 11:50:56 AM INFO: 		dq_init: False
07/19/2021 11:50:56 AM INFO: 		saturation: False
07/19/2021 11:50:56 AM INFO: 		ipc: False
07/19/2021 11:50:56 AM INFO: 		refpix: False
07/19/2021 11:50:56 AM INFO: 		superbias: False
07/19/2021 11:50:56 AM INFO: 		persistence: False
07/19/2021 11:50:56 AM INFO: 		dark_current: False
07/19/2021 11:50:56 AM INFO: 		linearity: False
07/19/2021 11:50:56 AM INFO: 		firstframe: False
07/19/2021 11:50:56 AM INFO: 		lastframe: False
07/19/2021 11:50:56 AM INFO: 		rscd: False
07/19/2021 11:50:56 AM INFO: 		jump: True
07/19/2021 11:50:56 AM INFO: 		rate: True
07/19/2021 11:50:56 AM INFO: 	Slope file outputs/dev/dark_monitor/data/nircam_nrca1_full/jw00759141001_03101_00001_nrca1_dark_rate.fits already exists. Skipping call to pipeline.
07/19/2021 11:50:56 AM INFO: 	Slope images to use in the dark monitor for nircam, NRCA1_FULL:
07/19/2021 11:50:56 AM INFO: 		outputs/dev/dark_monitor/data/nircam_nrca1_full/jw00759101001_02101_00001_nrca1_dark_rate.fits
07/19/2021 11:50:56 AM INFO: 		outputs/dev/dark_monitor/data/nircam_nrca1_full/jw00759103001_02101_00001_nrca1_dark_rate.fits
07/19/2021 11:50:56 AM INFO: 		outputs/dev/dark_monitor/data/nircam_nrca1_full/jw00673042001_04201_00001_nrca1_dark_rate.fits
07/19/2021 11:50:56 AM INFO: 		outputs/dev/dark_monitor/data/nircam_nrca1_full/jw00759143001_03101_00025_nrca1_dark_rate.fits

...

07/19/2021 11:51:51 AM INFO: Name of mean slope image: outputs/dev/dark_monitor/mean_slope_images/nircam_nrca1_full_57357.0_to_59414.658543569094_mean_slope_image.fits
07/19/2021 11:51:52 AM INFO: 	Sigma-clipped mean of the slope images saved to: outputs/dev/dark_monitor/mean_slope_images/nircam_nrca1_full_57357.0_to_59414.658543569094_mean_slope_image.fits
07/19/2021 11:51:52 AM INFO: Baseline filename: outputs/dev/dark_monitor/mean_slope_images/nircam_nrca1_full_57357.0_to_59411.75182531033_mean_slope_image.fits
07/19/2021 11:51:52 AM INFO: 	Baseline file is outputs/dev/dark_monitor/mean_slope_images/nircam_nrca1_full_57357.0_to_59411.75182531033_mean_slope_image.fits
07/19/2021 11:51:52 AM INFO: 	Found 0 new hot pixels
07/19/2021 11:51:52 AM INFO: 	Found 0 new dead pixels
07/19/2021 11:51:52 AM INFO: Adding 0 hot pixels to database.
07/19/2021 11:51:52 AM INFO: Adding 0 dead pixels to database.
07/19/2021 11:51:53 AM INFO: 	Found 0 new noisy pixels
07/19/2021 11:51:53 AM INFO: Adding 0 noisy pixels to database.
07/19/2021 11:51:53 AM INFO: 	Amplifier boundaries: {'1': [(4, 512, 1), (4, 2044, 1)], '2': [(512, 1024, 1), (4, 2044, 1)], '3': [(1024, 1536, 1), (4, 2044, 1)], '4': [(1536, 2044, 1), (4, 2044, 1)]}
07/19/2021 11:51:53 AM INFO: 	Full frame exposure detected. Adding the full frame to the list of amplifiers upon which to calculate statistics.
07/19/2021 11:51:54 AM WARNING: jwql-3.7/lib/python3.7/site-packages/astropy/modeling/fitting.py:1168: AstropyUserWarning: The fit may be unsuccessful; check fit_info['message'] for more information.
  AstropyUserWarning)

07/19/2021 11:51:54 AM CRITICAL: Traceback (most recent call last):
  File "jwql/jwql/utils/logging_functions.py", line 284, in wrapped
    func(*args, **kwargs)
  File "jwql/jwql/utils/logging_functions.py", line 249, in wrapped
    func(*args, **kwargs)
  File "dark_monitor.py", line 795, in run
    self.process(dark_files)
  File "dark_monitor.py", line 644, in process
    histogram, bins) = self.stats_by_amp(slope_image, amp_bounds)
  File "dark_monitor.py", line 986, in stats_by_amp
    amplitude, peak, width = calculations.gaussian1d_fit(bin_centers, hist, initial_params)
  File "jwql/jwql/utils/calculations.py", line 103, in gaussian1d_fit
    cov_diag = np.diag(fitter_gauss.fit_info['param_cov'])
  File "<__array_function__ internals>", line 6, in diag
  File "jwql-3.7/lib/python3.7/site-packages/numpy/lib/twodim_base.py", line 298, in diag
    raise ValueError("Input must be 1- or 2-d.")
ValueError: Input must be 1- or 2-d.

07/19/2021 11:51:54 AM CRITICAL: CRASHED
```

**Comment by bhilbert4** [comment]
Weird. I just ran `stats_by_amp()` locally using the mean slope image listed in the traceback above. Everything ran to completion with no issues.
