### ISSUE TITLE
Dark monitor failure with inserting array of int64 into database

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwql#776]
**Describe the bug**
A recent run of the dark current monitor failed when trying to insert new hot pixels into the database. The log file is:
logs/test/dark_monitor/dark_monitor_2021-07-29-13-06.log.

And the end of the traceback is:
07/29/2021 16:41:39 PM INFO:    Found 543446 new hot pixels
07/29/2021 16:41:39 PM INFO:    Found 513322 new dead pixels
07/29/2021 16:41:39 PM INFO: Adding 543446 hot pixels to database.
07/29/2021 16:41:40 PM CRITICAL: Traceback (most recent call last):
  File "sqlalchemy/engine/base.py", line 1706, in _execute_context
    cursor, statement, parameters, context
  File "sqlalchemy/engine/default.py", line 692, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: can't adapt type 'numpy.int64'

I've done some manual testing and have found that indeed, there is a numpy.where statement that is returning tuples of coordinates, where the coordinates are 64-bit integers:
https://github.com/spacetelescope/jwql/blob/develop/jwql/instrument_monitors/common_monitors/dark_monitor.py#L383

It's not clear to me whether this is an issue with the results from np.where changing (seems unlikely) or a problem with the database accepting 64-bit integers, or something else. The database table definition file only specifies the coordinates as integer arrays, with no mention of the sizes of the integers.

**Comment by bhilbert4** [comment]
Note that at the moment this bug appears only on the test server, and not the dev server.
